### ISSUE TITLE
Error in Generating protoTxt

### ISSUE THREAD

**Issue by zghn** [CMU-Perceptual-Computing-Lab/openpose_train#41]
Hi,
I wanna train the openpose with a new loss function. I've done the steps according to your suggestion but Generating protoTxt failed! 
would you help me please...
 so thanks

------------------------- Absolute paths: -------------------------
sCaffeFolder absolute path:	/openpose_train-master/openpose/3rdparty/caffe
sLmdbFolder absolute paths:
	../dataset/lmdb_coco2017_foot
	../dataset/lmdb_coco
	../dataset/lmdb_mpii
sLmdbBackground absolute path:	../dataset/lmdb_background
sPretrainedModelPath absolute path:	../dataset/vgg/VGG_ILSVRC_19_layers.caffemodel
sTrainingFolder absolute path:	../training_results/pose

modelNames: COCO_25B_23;COCO_25B_17;MPII_25B_16
lmdbFolders: ../dataset/lmdb_coco2017_foot;../dataset/lmdb_coco;../dataset/lmdb_mpii
scaleMins: 0.333333333333;0.333333333333;0.333333333333
scaleMaxs: 1.5;1.5;2.5
numberMaxOcclusions: 2
sigmas: 7.0
maxDegreeRotations: 45
 
.
.
.
loss 0 level 1
Traceback (most recent call last):
  File "d_setLayers.py", line 643, in <module>
    sDistanceChannels, not sAddMpii)
  File "/openpose_train-master/training/generateProtoTxt.py", line 30, in generateProtoTxt
    addBkgChannel)
  File "/openpose_train-master/training/generateProtoTxt.py", line 1451, in setLayersTwoBranches
    return str(caffeNet.to_proto())
  File "/openpose_train-master/openpose/3rdparty/caffe/python/caffe/net_spec.py", line 194, in to_proto
    top._to_proto(layers, names, autonames)
  File "/openpose_train-master/openpose/3rdparty/caffe/python/caffe/net_spec.py", line 98, in _to_proto
    return self.fn._to_proto(layers, names, autonames)
  File "/openpose_train-master/openpose/3rdparty/caffe/python/caffe/net_spec.py", line 157, in _to_proto
    assign_proto(layer, k, v)
  File "/openpose_train-master/openpose/3rdparty/caffe/python/caffe/net_spec.py", line 65, in assign_proto
    is_repeated_field = hasattr(getattr(proto, name), 'extend')

**Comment by Wangsj18** [comment]
You should use openpose_caffe_train rather than openpose/3rdparty/caffe.
