### ISSUE TITLE
some error with body_25 d_setLayers.py

### ISSUE THREAD

**Issue by perfyperfect** [CMU-Perceptual-Computing-Lab/openpose_train#8]
hi, when I running body_25 d_setLayers.py ,there is one error:
Traceback (most recent call last):
  File "d_setLayers.py", line 368, in <module>
    isFinalModel, numberIterations, maximumPafStage, sUsePReLU, extraGT, sFootParts, sFootPAFs)
  File "/home/openpose_train-master/experimental_models/body_25/training_results/generateProtoTxt.py", line 24, in generateProtoTxt
    usePReLU, extraGT, footParts, footPAFs)
  File "/home/openpose_train-master/experimental_models/body_25/training_results/generateProtoTxt.py", line 1196, in setLayersTwoBranches
    return str(caffeNet.to_proto())
  File "/home/openpose_caffe_train-master/python/caffe/net_spec.py", line 193, in to_proto
    top._to_proto(layers, names, autonames)
  File "/home/openpose_caffe_train-master/python/caffe/net_spec.py", line 97, in _to_proto
    return self.fn._to_proto(layers, names, autonames)
  File "/home/openpose_caffe_train-master/python/caffe/net_spec.py", line 156, in _to_proto
    assign_proto(layer, k, v)
  File "/home/openpose_caffe_train-master/python/caffe/net_spec.py", line 77, in assign_proto
    assign_proto(getattr(proto, name), k, v)
  File "/home/openpose_caffe_train-master/python/caffe/net_spec.py", line 79, in assign_proto
    setattr(proto, name, val)
TypeError: 2 has type int, but expected one of: bytes, unicode

**Comment by jpbillzhou** [comment]
I have the same issue as this. How do you fix it?

**Comment by zhongxiaofang-run** [comment]
I have the same issue as this. How do you fix it?please help @jpbillzhou @perfyperfect
